### ISSUE TITLE
AttributeError: module 'streamlit' has no attribute 'beta_columns'

### ISSUE THREAD

**Issue by johnfelipe** [garaujo94/breast-cancer-diagnostic#1]
apt install git python3-pip
    pip install streamlit
    
    
    git clone https://github.com/garaujo94/breast-cancer-diagnostic.git
    
    cd breast-cancer-diagnostic
    pip install -r requirements-streamlit.txt
    streamlit run app-streamlit.py

show me this

      You can now view your Streamlit app in your browser.
    
      Network URL: http://143.244.165.163:8501
      External URL: http://143.244.165.163:8501
    
    File not exist

in web deployment show this:

![SNAG-0711](https://user-images.githubusercontent.com/428820/122312035-0b6f4a00-ced9-11eb-8a9e-5a99f54f1966.png)

**Comment by garaujo94** [comment]
I think this might be because you are using your default environment to run the code and you may have some older version of streamlit running. Try forcing ` pip install streamlit == 0.82.0 ` or run the code through a venv or docker

**Comment by johnfelipe** [comment]
Can u share me commands for venv in python 3 and Ubuntu 20
Tnks

**Comment by garaujo94** [comment]
You can try something like:
`virtualenv --python=python3.8 venv`
`source venv/bin/activate`
`pip install -r requirements-streamlit.txt`
`streamlit run app-streamlit.py`

Or, after installing docker and docker compose, just use `docker-compose build` and `docker-compose up` to run
